### ISSUE TITLE
[Question] Unable to get Quart working with Docker

### ISSUE THREAD

**Issue by mathana96** [pgjones/quart#58]
Hi there, 

I am trying to get started with Quart using a Docker container. 

I created a simple Dockerfile called `api.dockerfile` as follows:

```
FROM python:3.7-alpine
COPY requirements.txt /
RUN pip install -r /requirements.txt
COPY . /app
WORKDIR /app
EXPOSE 5000
```

Within my `requirements.txt` I have a single entry called `quart`. 

I have a file called `app.py` taken from the documentation's Getting Started section:

```
from quart import Quart
  
app = Quart(__name__)

@app.route('/')
async def hello():
    return 'hello'

app.run()
```

I am running the `Dockerfile` using `docker-compose`. This is my `docker-compose.yml`:

```
version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    image: my_docker_quart_compose:latest
    volumes:
      - .:/app
    command: python app.py
    ports:
      - "5000:5000"
```

When I run `docker-compose up`, the sequence gets stuck as follows (`api-test` is my current directory):

```
Creating network "api-test_default" with the default driver
Creating api-test_api_1 ... done
Attaching to api-test_api_1
```

My machine is listening at port 5000, but I get an empty response from the server. 

I've tried the following with no luck:
* Without `docker-compose`
* Tried this image: https://github.com/cellerich/docker-quart
* And this: https://github.com/gnargnor/quart-boilerplate

Quart works perfectly without problems locally. 

I am not sure if I am missing something. Your input is much appreciated!
